import { Clinic } from "@/global/types";

export const searchData: Clinic[] = [
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 4",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 5 Dentalfsdfdfgdgf",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 4",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 5 Dentalfsdfdfgdgf",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 4",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Republica Smiles",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["certified", "anesthesia on-site"],
    clinic_image: "https://image.com/image.png",
    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["PrcoedureSpecific", "SearchTags"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $900 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation", ".", "No deposit"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "Advanced Cosmetic Dental",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
  {
    clinic_name: "clinic name 5 Dentalfsdfdfgdgf",
    clinic_one_liner: "Dental Reconstructive Specialists",
    clinic_texts: ["free virtual follow-ups ", "recently updated facility"],
    clinic_image: "https://image.com/image.png",

    clinic_location: {
      country: "Mexico",
      country_short: "MX",
      city: "Mexico City",
    },
    clinic_tags: ["Hot deal"],
    clinic_certifications: [
      "ISAPS Certified",
      "JCI Accredited",
      "Medical Travel Association",
    ],
    price: "Starting at $1200 USD",
    availability: "Availability for january",
    cancelation_text: ["Free cancellation"],
  },
];
